version: "3.8"

services:
  seismic-streamer:
    build: .
    container_name: seismic_streamer
    pull_policy: build
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_CONSUME_TOPIC=${KAFKA_CONSUME_TOPIC}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_CONSUMER_GROUP=${KAFKA_CONSUMER_GROUP}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    command: uvicorn main:app --host 0.0.0.0 --port 8014
    ports:
      - "8014:8014"
    networks:
      nginx-manager_customnetwork:
        ipv4_address: 172.20.0.134

networks:
  nginx-manager_customnetwork:
    external: true
